services:
  backend:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    restart: unless-stopped
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
