services:
  client:
    extends:
      file: ./client/docker-compose.yml
      service: client
  python-service:
    extends:
      file: ./python-service/docker-compose.yml
      service: python-service
